name: Probouzení Supabase Databáze

   on:
     schedule:
       - cron: '0 4 */3 * *'
     workflow_dispatch:

   jobs:
     ping:
       runs-on: ubuntu-latest
       steps:
         - name: Stáhnutí kódu z repozitáře
           uses: actions/checkout@v4

         - name: Nastavení Pythonu
           uses: actions/setup-python@v5
           with:
             python-version: '3.10'

         - name: Instalace Supabase knihovny
           run: pip install supabase

         - name: Spuštění ping skriptu
           env:
             SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
           run: python ping_supabase.py
